### ISSUE TITLE
Error in "python squelch_table_read.py"

### ISSUE THREAD

**Issue by frosty-13** [Tunas1337/UV-K5-Modded-Firmwares#61]
Hello. Help me please. When trying to read, the following error appears:
![271413379-f53db2c7-7ff4-4364-a6a3-db5f05e7c08a](https://github.com/Tunas1337/UV-K5-Modded-Firmwares/assets/88665246/5766a959-acc7-449a-8116-3156edfcc31f)

**Comment by frosty-13** [comment]
Dude, are you alive?

**Comment by Tunas1337** [comment]
Wow, what a relief! I was starting to worry that my lack of response for a whole _three_ days might have indicated that I must've passed away. But fear not, I am indeed alive and well!

Now, let's address your issue. It seems like you've stumbled upon a problem that arises because libuvk5 doesn't consider OSFW version numbers, since it was made before OSFW reported version numbers that didn't fit the format of the stock Quansheng firmware. How dare I overlook such a trivial detail and use the library as it is! Clearly, the author should have anticipated every possible scenario known to mankind.

Unfortunately, I regret to inform you that I am not at your beck and call 24/7. You see, I have this thing called a life, which occasionally demands my attention. On top of that, I have the audacity to attend college and juggle a bunch of other stuff. I know, I know, it's quite outrageous. So, while I appreciate your urgency, I'm afraid I don't have the time to delve into this matter right now.

However, fear not! If you strain yourself to wait patiently for just a little bit longer, @amnemonic may eventually find a moment to address this issue with _the library that this script depends on._ Until then, I suggest you explore other avenues or perhaps even contribute a fix yourself, over at https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/main/python-utils/libuvk5.py. After all, we're all just trying to survive in this chaotic world where Python scripts don't quite yet cater to every minute detail of our lives.

Best of luck with your endeavors, and may you find solace in the fact that I am indeed alive (for now).

**Comment by frosty-13** [comment]
Ohhh... Thank you for such a long and wonderful story. You spent a lot of time writing a novel about your life instead of trying to correct a mistake. I was very interested to know the details of your life (no). I will continue to look for a solution to the problem with these scripts. But anyway, thank you very much for these scripts, according to reviews they help people fix the problem with the squelch.

**Comment by Tunas1337** [comment]
Stop demanding that people who do stuff for free, in their spare time, fix stuff on _your_ schedule. Not to mention that what you outlined is not a problem in my code.
I gave you all of the details – if you want it fixed on your terms, fix it yourself.
